name: mcapi
version: 1.0
main: com.github.jenya705.mcapi.BukkitApplication
author: Jenya705
commands:
  mcapi:
    permission: mcapi.command
    usage: /mcapi
permissions:
  mcapi.command:
    default: op